### ISSUE TITLE
服务端请求地址这个怎么填写啊？

### ISSUE THREAD

**Issue by AndyNull** [yinMrsir/chunyu-cms#4]
服务端请求地址这个怎么填写啊？

**Comment by yinMrsir** [comment]
用户端: 在Nuxt-web目录中创建.env文件并写入BASE_URL=服务端请求地址, 不需要走代理可以直接修改nuxt.config.ts:文件中runtimeConfig.public.apiBase.
管理端: 在Vue3-admin目录中修改.env.development或.env.production

**Comment by AndyNull** [comment]
> 没，我的意思是填写什么地址，因为现在还不知道服务端得什么端口之类得信息，随便设置吗？

**Comment by yinMrsir** [comment]
服务端默认的是4000端口

**Comment by AndyNull** [comment]
哦哦，那一般就是127.0.0.1:4000吧😀
