### ISSUE TITLE
你好，这个视频上传怎么配置？可以支持上传到本地吗？

### ISSUE THREAD

**Issue by heehee365** [yinMrsir/chunyu-cms#8]
如题，另外希望增加一些文档，部署太费劲了

**Comment by heehee365** [comment]
我部署成功，但是上传文件老是报错....

**Comment by heehee365** [comment]
报错：演示环境,不允许操作，需要修改或设置哪个地方？

**Comment by yinMrsir** [comment]
Nest-server/src/config/config.production.ts 中&nbsp;isDemoEnvironment 配置是否是演示环境




rain
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yinMrsir/chunyu-cms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月4日(星期四) 下午5:44
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [yinMrsir/chunyu-cms] 你好，这个视频上传怎么配置？可以支持上传到本地吗？ (Issue #8)





 
报错：演示环境,不允许操作，需要修改或设置哪个地方？
